[Journal]
# Максимальный размер на диске
SystemMaxUse=1G

# Максимальный размер в памяти
RuntimeMaxUse=256M

# Максимальное время хранения логов
MaxRetentionSec=14d

# Минимальное свободное место (если меньше - начинает удалять)
SystemKeepFree=512M
RuntimeKeepFree=128M

# Уровень по умолчанию
MaxLevelStore=notice
MaxLevelSyslog=notice
MaxLevelKMsg=notice
MaxLevelConsole=notice
